### ISSUE TITLE
Glow tranquilizing shot when there is something to dispel

### ISSUE THREAD

**Issue by nickdekruijk** [xod-wow/LiteButtonAuras#16]
AdiButtonAura addon used to make my tranq shot button glow when mobs in m+ were enraging (the affix).
I really miss that now, is that something that can be added to litebuttonauras?

**Comment by mbattersby** [comment]
That's already supposed to be happening. It used to work, I wonder if something changed. I don't play any classes with a soothe and I'm not sure how to test it.

**Comment by mbattersby** [comment]
I just tried it with Shiv (Rogue) on a mob in Korthia that enrages itself, and it highlighted correctly. As far as I can tell it's working.

**Comment by nickdekruijk** [comment]
I noticed it glows on certain spells too but not the ragging affix. Maybe spell Id has changed? Are you using a library with spells to highlight that needs updating maybe?

**Comment by mbattersby** [comment]
No that sounds like some kind of nightmare! It's looking at the return values from the UnitAura API call, which has always returned a particular pattern (isStealable == true and dispelName == "") for enrages.

To fix it or see what's wrong I basically need the UnitAura output from the target buff, which is quite hard to get since I don't even do M+ much let alone have time in one to poke at a mob that's enraged.

If you feel keen to try to capture it you can put this on a macro, hit it while targeting something enraged, and send me what it says:

`/run for i = 1,5 do if UnitBuff('target', i) == 'Enrage' then DevTools_Dump(UnitBuff('target', i)) break end end`

Obviously I'll understand if you don't want to frizt your key timer by doing that.

**Comment by nickdekruijk** [comment]
Dump: value=AuraUtil.FindAuraByName('Enrage', 'target') 
[1]="Enrage", 
[2]=132117, 
[3]=0, 
[4]="", 
[5]=0, 
[6]=0, 
[7]="nameplate1", q
[8]=true, 
[9]=false, 
[10]=228318, 
[11]=false, 
[12]=false, 
[13]=false, 
[14]=false, 
[15]=1

**Comment by nickdekruijk** [comment]
Last day before reset so lowered my key to a 7 to test it out :)

**Comment by nickdekruijk** [comment]
@mbattersby did you have a chance to check it out? The raging affix is active again this week so if needed I can do some further testing.

**Comment by mbattersby** [comment]
I admit I totally forgot, I was very sick when you put in the bug report and didn't remember it existed. Oops.

Looks like the issue is that the enrage never expires, which is definitely a bug in LBA's detection. Once I've had enough coffee I'll get out a new version for you to test.

**Comment by mbattersby** [comment]
Please try 10.0.12 when you are able.

**Comment by nickdekruijk** [comment]
Yes it works! Thank you very much for the update!

**Comment by mbattersby** [comment]
Fantastic, thanks for helping with this.
