### ISSUE TITLE
DH Consume Magic 

### ISSUE THREAD

**Issue by HeymannM** [xod-wow/LiteButtonAuras#19]
Hi, I have a small problem of visibility with Consume Magic Dh ! 
I use Elvui and I really think the colour aura for this spell when we can dispell is almost invisible whereas it was clearly visible with AdiButtonAuraas.
Is there a special setting I could do by myself or this problem could be resolved by you ?
Ty for your answer and sorry for my english skill (I'm french ^^) !

**Comment by mbattersby** [comment]
I 100% agree. I logged something similar long ago in #8. It never made it to the top of my priorities.

Masque makes worse since it replaces the glow with something smaller. Not sure if you are using that.

Do you have a picture of what it used to look like with AdiButtonAuras to compare with what it looks like now? I'd like to fix it but I'm not sure what to do.

**Comment by mbattersby** [comment]
Also if you can paste a screenshot of how it looks now with your UI that would help.
