### ISSUE TITLE
Interrupts on cooldown shouldn't flash.

### ISSUE THREAD

**Issue by arcadepro** [xod-wow/LiteButtonAuras#2]
Interrupt spells should not flash if they're on cooldown.

**Comment by mbattersby** [comment]
I think the right answer is probably "should not flash unless the interrupt spell will come off cooldown before the spell to be interrupted finishes casting".

I definitely want to know if there's something I can interrupt, because sometimes I want to be spamming the interrupt button as it comes off cooldown because I can just sneak an interrupt in. I did think about this and how it works now is a deliberate decision  rather than an accident/bug.

I will consider the possibility of the cooldown vs cast time check. There are some awkward mob spells that have a cast immediately followed by a channel that might make this look weird.

**Comment by arcadepro** [comment]
In a solo scenario or in a pure emergency I agree; but in a team play situation (raid/m+) if you can't kick it's simply someone else's turn. You don't really need, or want, to know if your kick will _just_ about come off CD. For me, it's better to have the clarity that's it's just not your turn.

I think Adibuttonauras has a 'no flash on cooldown' tick box on it's main options page.

**Comment by mbattersby** [comment]
114225c / 9.1.5 now only shows flash if interrupt will be available before cast end.

I'm going to leave this open for a bit in case I change my mind after using it for a while. I appreciate your position, but I think this is the right behaviour even if it's not what you are used to.

**Comment by arcadepro** [comment]
That's cool. I will try it out!

**Comment by mbattersby** [comment]
It is not easy to be cautiously hubristic, when I know how much of a fool I will look when I'm wrong and change my mind. :)

**Comment by mbattersby** [comment]
Closing this off years later, still happy with how it works.
